default:
  image: openjdk:8-jdk

stages:
  - build
  - test

build project:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    name: build-artifacts
    expire_in: 1d
    paths:
      - build
      - livingdoc-*/build

test project:
  stage: test
  before_script:
    - python -m http.server 80 --bind 127.0.0.1 --directory livingdoc-sample/src/test/docs
  script:
    - ./gradlew check -x detekt
    - ./gradlew codeCoverageReport
  artifacts:
    name: test-artifacts
    expire_in: 1d
    paths:
      - build/reports/jacoco
    reports:
      junit:
        - livingdoc-*/build/test-results/test/TEST-*.xml

lint project:
  stage: test
  script:
    - ./gradlew detekt
