default:
  image: openjdk:8-jdk

stages:
  - build
  - test

build project:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    name: build-artifacts
    expire_in: 1d
    paths:
      - build
      - livingdoc-*/build

test project:
  stage: test
  script:
    - ./gradlew check -x detekt

lint project:
  stage: test
  script:
    - ./gradlew detekt
